# Generated by Django 3.0.1 on 2019-12-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='nullable', max_length=2058),
        ),
    ]
