# Generated by Django 3.0.1 on 2020-05-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20200530_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='name',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
